/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto1compiladores;

import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import org.antlr.v4.runtime.ANTLRInputStream;
import org.antlr.v4.runtime.CommonTokenStream;
import org.antlr.v4.runtime.DiagnosticErrorListener;
import org.antlr.v4.runtime.RecognitionException;
import org.antlr.v4.runtime.TokenStream;
import org.antlr.v4.runtime.atn.PredictionMode;
import org.antlr.v4.runtime.tree.ParseTree;
import org.antlr.v4.runtime.tree.ParseTreeWalker;

/**
 *
 * @author pablo
 */
public class TextEditorFrame extends javax.swing.JFrame {

    /**
     * Creates new form TextEditorFrame
     */
    public TextEditorFrame() {
        initComponents();
        error=false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        loadButton = new javax.swing.JButton();
        compileButton = new javax.swing.JButton();
        quitButton = new javax.swing.JButton();
        status = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        consoleArea = new javax.swing.JTextArea();
        MIPSpane = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        iCodeField = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        MIPSText = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        newButton.setText("New");
        newButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newButtonActionPerformed(evt);
            }
        });

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        loadButton.setText("Load");
        loadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadButtonActionPerformed(evt);
            }
        });

        compileButton.setText("Compile!");
        compileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compileButtonActionPerformed(evt);
            }
        });

        quitButton.setText("Quit");
        quitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitButtonActionPerformed(evt);
            }
        });

        status.setEditable(false);
        status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusActionPerformed(evt);
            }
        });

        jLabel1.setText("Status");

        consoleArea.setColumns(20);
        consoleArea.setRows(5);
        jScrollPane2.setViewportView(consoleArea);

        textArea.setColumns(20);
        textArea.setLineWrap(true);
        textArea.setRows(5);
        textArea.setWrapStyleWord(true);
        jScrollPane1.setViewportView(textArea);

        MIPSpane.addTab("Input", jScrollPane1);

        iCodeField.setColumns(20);
        iCodeField.setRows(5);
        jScrollPane3.setViewportView(iCodeField);

        MIPSpane.addTab("I-Code", jScrollPane3);

        MIPSText.setColumns(20);
        MIPSText.setRows(5);
        jScrollPane4.setViewportView(MIPSText);

        MIPSpane.addTab("MIPS", jScrollPane4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(newButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loadButton)
                .addGap(18, 18, 18)
                .addComponent(quitButton)
                .addGap(65, 65, 65)
                .addComponent(compileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
            .addComponent(MIPSpane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(newButton)
                        .addComponent(compileButton)
                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(loadButton)
                        .addComponent(quitButton))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(MIPSpane, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
                .addGap(13, 13, 13)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public JTextArea getConsole(){
        return consoleArea;
    
    }
    private void newButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newButtonActionPerformed
        textArea.setText("");
        status.setText("New File");
        
        
    }//GEN-LAST:event_newButtonActionPerformed

    private void statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusActionPerformed

    private void quitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitButtonActionPerformed
         System.exit(0);
    }//GEN-LAST:event_quitButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        JFileChooser chooser = new JFileChooser();
        int chooserValue = chooser.showSaveDialog(this);
        if(chooserValue == JFileChooser.APPROVE_OPTION){
            try {
                PrintWriter fout = new PrintWriter(chooser.getSelectedFile());
                fout.print(textArea.getText());
                fout.close();
                status.setText("Saved : " + chooser.getSelectedFile().getAbsolutePath());
                
            } catch (FileNotFoundException ex) {
                Logger.getLogger(TextEditorFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
        
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void loadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadButtonActionPerformed
        JFileChooser chooser = new JFileChooser();
        int chooserValue = chooser.showOpenDialog(this);
        if(chooserValue== JFileChooser.APPROVE_OPTION){
            try {
                Scanner fin = new Scanner(chooser.getSelectedFile());
                String buffer = "";
                while(fin.hasNext()){
                    buffer += fin.nextLine()+"\n";
                    
                            
                }
                textArea.setText(buffer);
                
                fin.close();
                status.setText("Loaded : " + chooser.getSelectedFile().getAbsolutePath());
                
            } catch (FileNotFoundException ex) {
                JOptionPane.showMessageDialog(this, "File Not Found");
            }
            
            
        
        }
    }//GEN-LAST:event_loadButtonActionPerformed

    private void compileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compileButtonActionPerformed
        this.error = false;
        String src = textArea.getText();
        consoleArea.setText("");
        iCodeField.setText("");
        this.MIPSText.setText("");
        Temp.disponibles.clear();
        Temp.tempNum=0;
        try{
            DECAFLexer lexer  = new DECAFLexer(new ANTLRInputStream(src));
            //lexer.removeErrorListeners();
            //lexer.addErrorListener(new ThrowingErrorListener(this));        
            TokenStream tokenStream = new CommonTokenStream(lexer);
            
            DECAFParser parser = new DECAFParser(tokenStream);
            parser.removeErrorListeners();
            parser.addErrorListener(new ThrowingErrorListener(this));
            
            
            
            parser.program()/*.inspect(parser)*/;
            if(!parser.getCurrentToken().getText().equals("<EOF>")){
                error = true;
                consoleArea.setText("ERROR:  Se llego al final del programa antes de finalizar input");
                
            }
            
            if (!error) {
                lexer = new DECAFLexer(new ANTLRInputStream(src));
                lexer.removeErrorListeners();
                //lexer.addErrorListener(new ThrowingErrorListener(this));      

                tokenStream = new CommonTokenStream(lexer);

                parser = new DECAFParser(tokenStream);
                parser.removeErrorListeners();
                //parser.addErrorListener(new ThrowingErrorListener(this));            
                ParseTree tree = parser.program();
                TypeChecker checker = new TypeChecker(this);


                Tipo t = checker.visit(tree);
                for(Ambito a: checker.ambitoGlobal.ambitosInternos){
                    if(a instanceof Estructura){
                        Estructura a1 = (Estructura)a;
                        System.out.println(a1.name+"-- "+a1.tipo.getWidth());
                        
                    }
                
                }
                System.out.print("  ");
                //Si no hay error de tipos iniciamos la generacion de codigo intermedio
               if(!t.equals(checker.ERROR)){
                    Temp.tempNum=0;
                    lexer = new DECAFLexer(new ANTLRInputStream(src));
                    lexer.removeErrorListeners();
                    //lexer.addErrorListener(new ThrowingErrorListener(this));      

                    tokenStream = new CommonTokenStream(lexer);

                    parser = new DECAFParser(tokenStream);
                    parser.removeErrorListeners();
                    //parser.addErrorListener(new ThrowingErrorListener(this));            
                    tree = parser.program();
                    ICGenerator gen = new ICGenerator(checker.ambitoGlobal,checker.globalSize);
                    IC c = gen.visit(tree);
                    int i=0;
                    for(Quad q:gen.programCode){
                        String s = i+". "+q.toString()+"\n";
                        this.iCodeField.append(s);
                        i++;
                    }
                    
                    //Procedemos a generara codigo objeto
                    CodeGenerator MIPSGen = new CodeGenerator(gen.programCode,gen.data,checker.ambitoActual);
                    MIPSGen.generateCode();
                    for(String s: MIPSGen.MIPScode){
                        this.MIPSText.append(s+"\n");
                    
                    }

                                     
                }

            }


            //consoleArea.setText(tree.toStringTree(parser));
        }
        catch(Exception e){
           
            consoleArea.setText(e.getMessage());
            e.printStackTrace();
            
            

           
        }
    }//GEN-LAST:event_compileButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TextEditorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TextEditorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TextEditorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TextEditorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TextEditorFrame().setVisible(true);
            }
        });
    }
    boolean error;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea MIPSText;
    private javax.swing.JTabbedPane MIPSpane;
    private javax.swing.JButton compileButton;
    private javax.swing.JTextArea consoleArea;
    private javax.swing.JTextArea iCodeField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton loadButton;
    private javax.swing.JButton newButton;
    private javax.swing.JButton quitButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField status;
    private javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables
}
